In [1]:
import numpy as np
import json

In [2]:
import numpy as np

def linear(x):
  """Fungsi aktivasi linear"""
  return (x)

def sigmoid(x):
  """Fungsi aktivasi sigmoid"""
  return (1 / (1 + np.exp(-x)))

def relu(x):
  """Fungsi aktivasi ReLU"""
  return (np.maximum(0, x))

def softmax(x):
  """Fungsi aktivasi softmax"""
  return (np.exp(x) / np.sum(np.exp(x)))

In [3]:
class Layer:
	def __init__(self, input_size, n_neuron, activation, input_data, weights, bias, output, max_sse):
		activations = {
			'linear': linear,
			'sigmoid': sigmoid,
			'relu': relu,
			'softmax': softmax,
			'None' : None
		}

		self.input_size = input_size
		self.n_neuron = n_neuron
		self.activation = activations[activation]
		self.input_data = input_data
		self.weights = weights
		self.bias = bias
		self.output = output
		self.max_sse = max_sse
		self.activation_value = None

In [4]:
class FeedForwardNeuralNetwork:
	def __init__(self):
		self.input_layer = []
		self.hidden_layer = []
		self.output_layer = []
		self.n_hidden_layer = 0
		self.activation_value = []
	
	def add_layer(self, layerType, input_size, n_neuron, activation, input_data, weights, bias, output, max_sse):
		if (layerType == "input_layer") :
			self.input_layer.append(Layer(input_size, n_neuron, activation, input_data, weights, bias, output, max_sse))
		elif (layerType == "hidden_layer") :
			self.hidden_layer.append(Layer(input_size, n_neuron, activation, input_data, weights, bias, output, max_sse))
			self.n_hidden_layer += 1
		elif (layerType == "output_layer") :
			self.output_layer.append(Layer(input_size, n_neuron, activation, input_data, weights, bias, output, max_sse))

	def forward_propagation(self, n_instance):
		for i in range (n_instance):
			print("Input layer")
			input_data = self.input_layer[0].input_data

			print("Input data yang ke-" + str(i+1) + " berupa" , input_data[0])
			print("=========================================================")

			for j in range (self.n_hidden_layer) :
				print("Hidden layer yang ke-" + str(j+1))

				print("Berikut informasi yang terdapat pada hidden layer tersebut")
				
				print("Weight = ")
				weight = self.hidden_layer[j].weights
				print(weight)

				print("Bias = ")
				bias = self.hidden_layer[j].bias
				print(bias)

				print("=========================================================")
				print("Diperoleh nilai sigma = ")
				if (j == 0) :
					sigma = np.dot(input_data, weight) + bias
				else :
					sigma = np.dot(activation_value, weight) + bias
				print(sigma)

				print("Diperoleh nilai fungsi aktivasi = ")
				activation_value = (self.hidden_layer[j].activation(sigma))
				print(list(activation_value[0]))
				print("=========================================================")

			self.activation_value.append(list(activation_value[0]))

	def printListActivationValue(self) :
		print("Berikut nilai output yang diperoleh dari input yang telah diberikan")
		print(self.activation_value)
		print("=========================================================")
	
	def accuracy(self) :
		expectOutput = self.output_layer[0].output
		nTotal = len(expectOutput)
		nAccurate = 0
		for i in range (nTotal) :
			for j in range (len(expectOutput[i])) :
				if (float(expectOutput[i][j]) == float(self.activation_value[i][j])) :
					nAccurate = nAccurate + 1
		
		percentAccurate = (nAccurate / nTotal ) * 100
		print("Akurasi yang diperoleh senilai " + str(percentAccurate) + "%")

In [5]:
#Fungsi membaca input file

def generate_model(filename):
	model = open(filename)
	model_data = json.loads(model.read())
	model.close()

	ffnn = FeedForwardNeuralNetwork()

	for x in model_data: # case dan expect
		for y in model_data[str(x)] : # model, input, weights, output, max_sse
			if (str(y) == "model") :
				for z in (model_data[str(x)])[str(y)] : #input_size, layers
					if (str(z) == "layers" ) : # array of list
						activation_function = []
						n_neuron = []
						for j in ((model_data[str(x)])[str(y)])[str(z)] :
							activation_function.append(j['activation_function'])
							n_neuron.append(j['number_of_neurons'])
					else : # "input_size"
						input_size = ((model_data[str(x)])[str(y)])[str(z)]
			elif (str(y) == 'input'):
					input_data = ((model_data[str(x)])[str(y)])
			elif (str(y) == 'weights'):
				bias = []
				weights = []
				for z in range(len(((model_data[str(x)])[str(y)]))) :
					bias_temp = []
					weights_temp = []
					for i in range(len((((model_data[str(x)])[str(y)]))[z])) :
						if ( i == 0 ):
							bias_temp.append(((((model_data[str(x)])[str(y)][z][i]))))
						else :
							weights_temp.append(((((model_data[str(x)])[str(y)][z][i]))))
					bias.append(bias_temp)
					weights.append(weights_temp)
			elif (str(y) == 'output'):
				output = ((model_data[str(x)])[str(y)])
			elif (str(y) == 'max_sse'):
				max_sse = ((model_data[str(x)])[str(y)])

	# Input Layer
	ffnn.add_layer( 'input_layer', input_size=int(input_size), n_neuron=None, activation='None', input_data=(input_data), weights=None, bias=None, output=None, max_sse=None )

	# Hidden Layer
	for i in range (len(weights)) :
		ffnn.add_layer( 'hidden_layer', input_size=None, n_neuron=int(n_neuron[i]), activation=str(activation_function[i]), input_data=None, weights=(weights[i]), bias=(bias[i]), output=None, max_sse=None )

	# Output Layer
	ffnn.add_layer( 'output_layer', input_size=None, n_neuron=None, activation='None', input_data=None, weights=None, bias=None, output=output, max_sse=max_sse )

	return ffnn


In [6]:
while True :
  model = str(input("Masukkan model yang ingin digunakan (Silakan cek nama file yang ada pada folder model): "))

  if (model == 'relu'):
    break
  elif (model == 'sigmoid'):
    break
  elif (model == 'softmax'):
    break
  elif (model == 'linear'):
    break
  elif (model == 'multilayer'):
    break
  else :
    print("Input yang diberikan salah")

ffnn = generate_model(filename=f"model/{model}.json")

while True :
  n_instance = str(input("Masukkan jumlah instance yang akan diprediksi: "))

  if (int(n_instance) <= len(ffnn.input_layer[0].input_data) and int(n_instance) >= 1):
    print("=========================================================")
    break
  else :
    print("Input yang diberikan salah")

Masukkan model yang ingin digunakan (Silakan cek nama file yang ada pada folder model): multilayer
Masukkan jumlah instance yang akan diprediksi: 3


In [7]:
#Proses Forward Propagation bekerja
ffnn.forward_propagation(int(n_instance))

Input layer
Input data yang ke-1 berupa [1.0, 0.0]
Hidden layer yang ke-1
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[0.0, -2.0], [-1.0, 0.0]]
Bias = 
[[0.5, 0.5]]
Diperoleh nilai sigma = 
[[ 0.5 -1.5]
 [-0.5  0.5]
 [ 0.5  0.5]]
Diperoleh nilai fungsi aktivasi = 
[0.5, -1.5]
Hidden layer yang ke-2
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[0.0, -3.0], [-1.0, 0.0]]
Bias = 
[[0.5, 0.5]]
Diperoleh nilai sigma = 
[[ 2. -1.]
 [ 0.  2.]
 [ 0. -1.]]
Diperoleh nilai fungsi aktivasi = 
[2.0, 0.0]
Input layer
Input data yang ke-2 berupa [1.0, 0.0]
Hidden layer yang ke-1
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[0.0, -2.0], [-1.0, 0.0]]
Bias = 
[[0.5, 0.5]]
Diperoleh nilai sigma = 
[[ 0.5 -1.5]
 [-0.5  0.5]
 [ 0.5  0.5]]
Diperoleh nilai fungsi aktivasi = 
[0.5, -1.5]
Hidden layer yang ke-2
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[0.0, -3.0], [-1.0, 0.0]]
Bias = 
[[0.5, 0.5]]
Diperoleh

In [8]:
#Menampilkan nilai aktivasi yang diperoleh dari setiap input data
ffnn.printListActivationValue()

Berikut nilai output yang diperoleh dari input yang telah diberikan
[[2.0, 0.0], [2.0, 0.0], [2.0, 0.0]]


In [9]:
#Menampilkan akurasi yang didapatkan berdasarkan input data
ffnn.accuracy()

Akurasi yang diperoleh senilai 100.0%
