In [11]:
import numpy as np
import json

In [12]:
#activation

def linear(x):
    return (x)

def sigmoid(x):
    return (1 / (1 + np.exp(-x)))

def ReLU(x):
    return (np.maximum(0, x))

def softmax(x):
    return (np.exp(x) / np.sum(np.exp(x)))

In [13]:
#class layer

class Layer:
    def __init__(self, n_neuron, activation, X=None, Y=None, weights=None, bias=None):
        activations = {
            'linear': linear,
            'sigmoid': sigmoid,
            'ReLU': ReLU,
            'softmax': softmax
        }

        if(n_neuron < 1):
            raise ValueError("Neuron tidak boleh lebih kecil dari 1")
        elif(activation not in ('linear', 'sigmoid', 'ReLU', 'softmax')):
            raise ValueError("Fungsi aktivasi tidak boleh selain dari salah satu diantara berikut, 'linear', 'sigmoid', 'ReLU', 'softmax'")
        else:
            self.n_neuron = n_neuron
            self.X = X
            self.Y = Y
            self.weights = weights
            self.bias = bias
            self.activation = activations[activation]
            self.activation_value = None

In [14]:
#class FFNN

class FeedForwardNeuralNetwork:
    def __init__(self):
        self.input_layer = []
        self.hidden_layer = []
        self.output_layer = []
        self.n_input_layer = 0
        self.n_hidden_layer = 0
        self.n_output_layer = 0
        self.activation_value = []

    def add_layer(self, layerType, n_neuron, activation, X=None, Y=None, weights=None, bias=None):
        if (layerType == "input_layer") :
            self.input_layer.append(Layer(n_neuron=n_neuron, activation=activation, X=X, Y=Y, weights=None, bias=bias))
            self.n_input_layer += 1
        elif (layerType == "hidden_layer") :
            self.hidden_layer.append(Layer(n_neuron=n_neuron, activation=activation, X=None, Y=None, weights=weights, bias=bias))
            self.n_hidden_layer += 1
        elif (layerType == "output_layer") :
            self.output_layer.append(Layer(n_neuron=n_neuron, activation=activation, X=None, Y=None, weights=weights, bias=None))
            self.n_output_layer += 1

    def predict(self, n_instance):
        for i in range (n_instance):
            print("Input layer")
            listData = self.input_layer[0].X

            X = np.array([listData[i]])
            print("Input data yang ke-" + str(i+1) + " berupa" , X[0])
            print("=========================================================")

            for j in range (self.n_hidden_layer) :
                listWeight = self.hidden_layer[j].weights
                listBias = self.input_layer[j].bias
                print("Hidden layer yang ke-" + str(j+1))
                print("Berikut informasi yang terdapat pada hidden layer tersebut")
                print("Weight = ")
                print(listWeight)
                print("Bias = ")
                print(listBias)
                print("=========================================================")
                print("Diperoleh nilai sigma = ")
                sigma = np.dot(X, listWeight) + listBias
                print(sigma)
                print("Diperoleh nilai fungsi aktivasi = ")
                activation_value = self.hidden_layer[j].activation(sigma)
                print(activation_value)
                print("=========================================================")

            listWeight = self.output_layer[j].weights
            listBias = self.hidden_layer[j].bias
            print("Output layer")
            print("Berikut informasi yang terdapat pada output layer")
            print("Weight = ")
            print(listWeight)
            print("Bias = ")
            print(listBias)
            print("=========================================================")
            print("Diperoleh nilai sigma = ")
            sigma = np.dot(activation_value, listWeight) + listBias
            print(sigma)

            activation_value = round((self.hidden_layer[j].activation(sigma))[0][0])
            print("Diperoleh nilai fungsi aktivasi =", activation_value)
            self.activation_value.append(activation_value)
            print("=========================================================")

    def printListActivationValue(self) :
        print("Berikut nilai output yang diperoleh dari input yang telah diberikan")
        print(self.activation_value)
        print("=========================================================")

    def accuracy(self) :
        listTargetFunction = self.input_layer[0].Y
        nTotal = len(listTargetFunction)
        nAccurate = 0
        for i in range (nTotal) :
            if (listTargetFunction[i] == self.activation_value[i]) :
                nAccurate = nAccurate + 1

        percentAccurate = (nAccurate / nTotal ) * 100
        print("Akurasi yang diperoleh senilai " + str(percentAccurate) + "%")

In [15]:
#Fungsi membaca input file

def generateModelFile(filename):
    model = open(filename)
    model_data = json.loads(model.read())
    model.close()

    ffnn = FeedForwardNeuralNetwork()

    for layer in model_data:
        typeLayer = model_data[str(layer)]
        if (str(layer) == 'input_layer') :
            ffnn.add_layer( str(layer), n_neuron=int(typeLayer['n_neuron']), activation=typeLayer['activation'], X=np.array(typeLayer['X']), Y=np.array(typeLayer['Y']), weights=None, bias=np.array(typeLayer['bias']) )
        elif (str(layer) == 'hidden_layer') :
            ffnn.add_layer( str(layer), n_neuron=int(typeLayer['n_neuron']), activation=typeLayer['activation'], X=None, Y=None, weights=np.array(typeLayer['weights']), bias=np.array(typeLayer['bias']) )
        elif (str(layer) == 'output_layer') :
            ffnn.add_layer( str(layer), n_neuron=int(typeLayer['n_neuron']), activation=typeLayer['activation'], X=None, Y=None, weights=np.array(typeLayer['weights']), bias=None )

    return ffnn

In [16]:
while True :
  model = str(input("Masukkan model yang ingin digunakan (Silakan cek nama file yang ada pada folder model): "))

  if (model == 'ReLU'):
    break
  elif (model == 'sigmoid'):
    break
  else :
    print("Input yang diberikan salah")

ffnn = generate_model(filename=f"model/{model}.json")

while True :
  n_instance = str(input("Masukkan jumlah instance yang akan diprediksi: "))

  if (int(n_instance) <= len(ffnn.input_layer[0].X) and int(n_instance) >= 1):
    print("=========================================================")
    break
  else :
    print("Input yang diberikan salah")

Masukkan model yang ingin digunakan (Silakan cek nama file yang ada pada folder model): ReLU
Masukkan jumlah instance yang akan diprediksi: 4


In [17]:
#Proses Forward Propagation bekerja
ffnn.predict(int(n_instance))

Input layer
Input data yang ke-1 berupa [0 0]
Hidden layer yang ke-1
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[1 1]
 [1 1]]
Bias = 
[ 0 -1]
Diperoleh nilai sigma = 
[[ 0 -1]]
Diperoleh nilai fungsi aktivasi = 
[[0 0]]
Output layer
Berikut informasi yang terdapat pada output layer
Weight = 
[[ 1]
 [-2]]
Bias = 
[0]
Diperoleh nilai sigma = 
[[0]]
Diperoleh nilai fungsi aktivasi = 0
Input layer
Input data yang ke-2 berupa [0 1]
Hidden layer yang ke-1
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[1 1]
 [1 1]]
Bias = 
[ 0 -1]
Diperoleh nilai sigma = 
[[1 0]]
Diperoleh nilai fungsi aktivasi = 
[[1 0]]
Output layer
Berikut informasi yang terdapat pada output layer
Weight = 
[[ 1]
 [-2]]
Bias = 
[0]
Diperoleh nilai sigma = 
[[1]]
Diperoleh nilai fungsi aktivasi = 1
Input layer
Input data yang ke-3 berupa [1 0]
Hidden layer yang ke-1
Berikut informasi yang terdapat pada hidden layer tersebut
Weight = 
[[1 1]
 [1 1]]
Bias = 
[ 0 -1]
Diperoleh

In [18]:
#Menampilkan nilai aktivasi yang diperoleh dari setiap input data
ffnn.printListActivationValue()

Berikut nilai output yang diperoleh dari input yang telah diberikan
[0, 1, 1, 0]


In [19]:
#Menampilkan akurasi yang didapatkan berdasarkan input data
ffnn.accuracy()

Akurasi yang diperoleh senilai 100.0%
